---
- hosts: all
  gather_facts: no
  remote_user: vagrant

  tasks:
    - name: run ssh-keyscan to add keys to known_hosts
      local_action: shell ssh-keyscan gitlab.local gitlab-runner.local DevSecOps-Box.local > ~/.ssh/known_hosts

    - name: install ssh key
      authorized_key: user=vagrant
                      key="{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}"
                      state=present
