---
- src: geerlingguy.pip
  version: 1.3.0

- src: geerlingguy.ruby
  version: 2.6.0

- src: geerlingguy.docker
  version: 2.7.0

- src: geerlingguy.packer
  version: 1.0.2

- src: geerlingguy.java
  version: 1.9.7

- src: geerlingguy.jenkins
  version: 4.3.0 

- src: geerlingguy.nginx
  version: 2.7.0 

- src: geerlingguy.elasticsearch
  version: 4.1.1

- src: geerlingguy.kibana
  version: 4.0.1

- src: geerlingguy.logstash
  version: 5.0.3

- src: secfigo.terraform
  version: 1.0.1

- src: secfigo.inspec
  version: 1.0.2
